[package]
name = "ruxel"
version = "0.1.0"
authors = ["toonnyy8"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlua = "0.17.0"
termion = "1.5.5"
